language: ruby
rvm:
  - 2.5
gemfile:
  - gemfiles/asciidoctor_2.0.11.gemfile
  - gemfiles/asciidoctor_2.0.12.gemfile
  - gemfiles/asciidoctor_2.0.13.gemfile
  - gemfiles/asciidoctor_2.0.14.gemfile
  - gemfiles/asciidoctor_2.0.15.gemfile
  - gemfiles/asciidoctor_2.0.16.gemfile
  - gemfiles/asciidoctor_2.0.17.gemfile
